// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Nomiki.Api.InterestRate.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Nomiki.Api.InterestRate.Database.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260131213853_InterestRateDefinitionUniqueFromTo")]
    partial class InterestRateDefinitionUniqueFromTo
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Nomiki.Api.InterestRate.Domain.InterestRateDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AdministrativeAct")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("administrative_act");

                    b.Property<decimal>("ContractualRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("contractual_rate");

                    b.Property<decimal>("DefaultRate")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("default_rate");

                    b.Property<string>("DeterministicHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("deterministic_hash");

                    b.Property<string>("Fek")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("fek");

                    b.Property<DateOnly>("From")
                        .HasColumnType("date")
                        .HasColumnName("from");

                    b.Property<DateOnly?>("To")
                        .HasColumnType("date")
                        .HasColumnName("to");

                    b.HasKey("Id")
                        .HasName("pk_interest_rate_definition");

                    b.HasIndex("From", "To")
                        .IsUnique()
                        .HasDatabaseName("ix_interest_rate_definition_from_to");

                    b.ToTable("interest_rate_definition", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
